### ISSUE TITLE
FE is not rendering User data

### ISSUE THREAD

**Issue by Pav0l** [lambdalabs-eu1-webchat/webchat-frontend#12]
**How to reproduce the bug:**
- visit https://webchatlabs.netlify.com/

The Inspect Element shows only `<div id='root'></div>` without any content.

Back end server does have data available (https://web-chat-labs.herokuapp.com/api/users).

![image](https://user-images.githubusercontent.com/38439473/56869236-4e6eba80-69fe-11e9-9f70-e9e4941805f9.png)

**Comment by ConConRob** [comment]
The Huroku free server sleeps. The first request to the server while it is sleeping takes a while because the server has to wake up

**Comment by Pav0l** [comment]
Needs to add a condition to use Redux Dev Tools only in `development` mode

**Comment by Pav0l** [comment]
Fixed with #16
