### ISSUE TITLE
Replace alerts with restriction modals

### ISSUE THREAD

**Issue by mark-marshall** [lambdalabs-eu1-webchat/webchat-frontend#170]
Currently, invalid email addresses and guests with no chat history cause alert messages in the window, these should be replaced with the warning/restriction modal

**Comment by Pav0l** [comment]
Also add restricted modal instead of alert here
![image](https://user-images.githubusercontent.com/38439473/58025432-c66b6480-7b14-11e9-87de-093f508215ca.png)
